color: null
fieldLayouts:
  71660a2a-5e9c-456e-9584-e81e70baf6f2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-13T16:04:50+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0cf026d5-6d08-4e27-8a1f-ab30bca41c98
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-14T12:19:11+00:00'
            elementCondition: null
            fieldUid: 36f64220-1754-471a-8655-6907cc37c65c # Abschnitte
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aaad723f-2d56-4832-bea7-bf2e181f48bb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0102572d-d127-40b1-b9c0-704387cc932f
        userCondition: null
handle: default
hasTitleField: true
icon: chimney
name: Standardseite
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
