color: null
fieldLayouts:
  2b120371-6d40-4a00-a1e6-f4375377574e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-14T12:11:23+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Überschrift
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e15c24e8-0518-4f3e-bf5b-d77911baae66
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-14T12:14:02+00:00'
            elementCondition: null
            fieldUid: f3e544b8-88bf-4761-8df2-d767fa1502b7 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1111b334-4fd4-442b-8a0c-e0a6eef0a2e4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-14T12:14:02+00:00'
            elementCondition: null
            fieldUid: 0b199c11-0b79-4e4b-b931-f9c85e23a667 # Link / Button
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0581690c-bbd8-470f-99eb-55979e9043c4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-14T12:14:02+00:00'
            elementCondition: null
            fieldUid: 6d792fe4-471d-48ed-bc45-5fe112ba7e46 # Bild
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e126f0af-7cdd-4c39-bb01-e4cd495a2ffd
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 53e75b8a-a78c-452c-911d-758bce643289
        userCondition: null
handle: hero
hasTitleField: true
icon: mask
name: Hero
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
