color: null
fieldLayouts:
  b842f94f-1052-4f8b-b66e-22aa349fb4b2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-03-31T07:42:51+00:00'
            elementCondition: null
            fieldUid: 0b2eb52b-6305-475a-a893-015343c2face # Abstand oben
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 10114274-7c59-4a02-afea-5a83a1804af0
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-03-31T07:42:51+00:00'
            elementCondition: null
            fieldUid: c4366270-fb71-48ba-ba8f-f8c33149b695 # Abstand unten
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6948cfd7-a2f1-44f9-aea1-26652cae87d0
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-03-31T09:34:05+00:00'
            elementCondition: null
            fieldUid: 1362616b-abbf-4bce-aa51-c6e365d9dda7 # Preise
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f5a604e8-1f33-483a-8f07-f3b56641e798
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: def389c8-d05e-4736-9b00-b5962d49715a
        userCondition: null
handle: pricing
hasTitleField: false
icon: null
name: Preistabelle
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
