color: null
fieldLayouts:
  b842f94f-1052-4f8b-b66e-22aa349fb4b2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-14T15:00:15+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d0f73118-93d0-4384-838c-764a05d65c20
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: def389c8-d05e-4736-9b00-b5962d49715a
        userCondition: null
handle: pricing
hasTitleField: true
icon: null
name: Preistabelle
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
