color: null
fieldLayouts:
  0ceebaeb-67d4-4c54-aeac-71efbde11742:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-03T15:30:12+00:00'
            elementCondition: null
            fieldUid: 7f0dd947-99d8-4456-93f3-4ce4f6162a3f # Rich Text - Einfach
            handle: text
            includeInCards: false
            instructions: null
            label: Text
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7f4dee26-b8cc-4390-b30f-3b70cc92b5c0
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: b0ea3afe-4b56-4064-8a17-f611689da0f2
        userCondition: null
handle: slide
hasTitleField: false
icon: null
name: Slide
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
