color: null
fieldLayouts:
  b930e811-f258-4bf5-9d17-cd79740cad03:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-03-31T13:27:39+00:00'
            elementCondition: null
            fieldUid: 0b2eb52b-6305-475a-a893-015343c2face # Abstand oben
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: df1fe6d9-9658-462e-ae6b-41f86df98659
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-03-31T13:27:39+00:00'
            elementCondition: null
            fieldUid: c4366270-fb71-48ba-ba8f-f8c33149b695 # Abstand unten
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 651b126e-8b72-4322-98f4-ac1b410a286a
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-03-28T15:20:41+00:00'
            elementCondition: null
            fieldUid: 3ae1a988-07ef-40a0-8438-62f2201ac267 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bc41f1ad-eda8-46b2-af90-766046942ff1
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 515b4b69-b07f-4cbe-9a92-0dc5a3b69308
        userCondition: null
handle: text
hasTitleField: false
icon: null
name: Text
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
