columnSuffix: null
handle: alignment
instructions: null
name: Ausrichtung
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Links
        -
          - value
          - left
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Mitte
        -
          - value
          - center
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Rechts
        -
          - value
          - right
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
