columnSuffix: null
handle: padding
instructions: null
name: Abstand
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - 'Oben & Unten'
        -
          - value
          - topBottom
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Oben
        -
          - value
          - top
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Unten
        -
          - value
          - bottom
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Keiner
        -
          - value
          - none
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
