columnSuffix: null
handle: sliderType
instructions: null
name: Slider-Typ
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - 'Aktuellste Blogposts'
        -
          - value
          - blogposts
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Text
        -
          - value
          - text
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
