dateModified: 1741969535
email:
  fromEmail: $CRAFT_SYSTEM_EMAIL
  fromName: $CRAFT_SITE_NAME
  replyToEmail: null
  template: _emails/system.twig
  transportSettings:
    command: '/usr/local/bin/mailpit sendmail -t --smtp-addr 127.0.0.1:1025'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  local:
    hasUrls: true
    name: Local
    settings:
      path: $FILESYSTEM_LOCAL_BASE_PATH
    type: craft\fs\Local
    url: $FILESYSTEM_LOCAL_BASE_URL
  servd:
    hasUrls: true
    name: Servd
    settings:
      errorMessage: 'Unable to find component class ''servd\AssetStorage\AssetsPlatform\Fs''.'
      expectedType: servd\AssetStorage\AssetsPlatform\Fs
      settings:
        __assoc__:
          -
            - cdnUrlPattern
            - ''
          -
            - customSubfolder
            - ''
          -
            - makeUploadsPublic
            - true
          -
            - optimisePrefix
            - ''
          -
            - optimiseUrlPattern
            - ''
          -
            - projectSlug
            - ''
          -
            - securityKey
            - ''
          -
            - subfolder
            - /local/
    type: craft\fs\MissingFs
    url: 'https://cdn2.assets-servd.host/'
meta:
  __names__:
    0b199c11-0b79-4e4b-b931-f9c85e23a667: 'Link / Button' # Link / Button
    5cbe08b7-b4bd-4a6b-be41-de9647b5eb19: Bilder # Bilder
    6d792fe4-471d-48ed-bc45-5fe112ba7e46: Bild # Bild
    7b662bcd-ea91-4c91-86ce-c60348c664d1: Seiten # Seiten
    7bf65ac5-9169-4bf8-8825-65fadd566946: New # New
    7f0dd947-99d8-4456-93f3-4ce4f6162a3f: 'Rich Text - Einfach' # Rich Text - Einfach
    8b610edc-f2dd-46b6-9597-96fcbb6d302a: Simple # Simple
    08c386f4-5a41-4c9f-8282-f6785af06bfc: 'Craft CMS Starter' # Craft CMS Starter
    19d6d897-1cde-4d59-914a-2bf8a23e7916: 'Public Schema' # Public Schema
    36f64220-1754-471a-8655-6907cc37c65c: Abschnitte # Abschnitte
    42eea3c2-2f84-43d8-a495-647d4994a8d5: 'Text - mehrzeilig' # Text - mehrzeilig
    79ca1e6a-abf2-498c-90bc-4808b357e371: Hauptnavigation # Hauptnavigation
    364db758-c9ca-4923-8a45-9ff5998f1177: Hero # Hero
    453f9294-407d-405a-b73b-d5b63aec2eaa: SEO # SEO
    502c0610-e74d-4359-8524-5652307ada64: Abstand # Abstand
    a9e047c8-1338-4261-9956-7e19d74fe428: Startseite # Startseite
    b9ac68e1-d9f1-4007-843f-fde1e9f4921b: Files # Files
    bdf6317d-0df7-449f-a937-a1a274ffb106: Standardseite # Standardseite
    cb6226c7-5901-41ed-ba28-a78b9504a3df: Images # Images
    d99bf7af-1eb1-4b77-814e-624eeec1a0e3: $CRAFT_SITE_NAME # $CRAFT_SITE_NAME
    da9f3d8e-5ba9-4eb9-a423-6ea09ddaed21: Formular # Formular
    f3e544b8-88bf-4761-8df2-d767fa1502b7: Text # Text
    f11d8cff-ef16-421a-bd8e-0b5ef8bf7d35: Preistabelle # Preistabelle
    fb0420bb-0fbf-46d2-afd2-f7992c60c886: 'Contact Form' # Contact Form
plugins:
  blitz:
    edition: standard
    enabled: true
    licenseKey: XO8E4093H0FPPEWU31U2S5HZ
    schemaVersion: 5.9.0
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  formie:
    edition: standard
    enabled: true
    licenseKey: OMBPJ4OA1BIW3HI7IWXHBC3R
    schemaVersion: 3.4.8
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  navigation:
    edition: standard
    enabled: true
    licenseKey: HQ90KEZT3AIEK7CQ0VQX7D9D
    schemaVersion: 2.1.0
  seomatic:
    edition: standard
    enabled: true
    licenseKey: 795D0IRXMO0BEU95Z64ILX03
    schemaVersion: 3.0.12
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: $CRAFT_SITE_NAME
  retryDuration: null
  schemaVersion: 5.6.0.2
  timeZone: America/Los_Angeles
