defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: bdf6317d-0df7-449f-a937-a1a274ffb106 # Seitenblöcke
handle: startseite
maxAuthors: 1
name: Startseite
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primäre Eintrag Seite'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  08c386f4-5a41-4c9f-8282-f6785af06bfc: # Craft CMS Starter
    enabledByDefault: true
    hasUrls: true
    template: startseite/_entry.twig
    uriFormat: __home__
type: single
