tabs:
  -
    elementCondition: null
    elements:
      -
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        dateAdded: '2025-03-14T16:24:35+00:00'
        disabled: false
        elementCondition: null
        id: null
        includeInCards: false
        inputType: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        providesThumbs: false
        readonly: false
        requirable: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\addresses\LabelField
        uid: 026e701f-774e-4776-a53b-8e514f32a097
        userCondition: null
        warning: null
        width: 100
      -
        attribute: countryCode
        dateAdded: '2025-03-14T16:24:35+00:00'
        elementCondition: null
        id: null
        includeInCards: false
        instructions: null
        label: null
        orientation: null
        providesThumbs: false
        requirable: false
        tip: null
        type: craft\fieldlayoutelements\addresses\CountryCodeField
        uid: aecc6ac7-170f-40e6-a13a-39585081dfae
        userCondition: null
        warning: null
        width: 100
      -
        dateAdded: '2025-03-14T16:24:35+00:00'
        elementCondition: null
        includeInCards: true
        instructions: null
        label: null
        providesThumbs: false
        required: false
        tip: null
        type: craft\fieldlayoutelements\addresses\AddressField
        uid: 40ddb5ef-b153-4a3f-a792-6c705d175701
        userCondition: null
        warning: null
    name: Inhalt
    uid: f1e9fc92-f7a1-4e6f-9ab8-f501b741230c
    userCondition: null
